# vcpkg iOS triplets for owalkie-core session (Boost.Beast + Opus).
# Install: flutter-client/ios/scripts/build-ios-deps.sh

function(owalkie_resolve_vcpkg_root out_var)
    if(DEFINED ENV{VCPKG_ROOT} AND NOT "$ENV{VCPKG_ROOT}" STREQUAL "")
        set(${out_var} "$ENV{VCPKG_ROOT}" PARENT_SCOPE)
    elseif(DEFINED OWALKIE_VCPKG_ROOT_DEFAULT AND NOT "${OWALKIE_VCPKG_ROOT_DEFAULT}" STREQUAL "")
        set(${out_var} "${OWALKIE_VCPKG_ROOT_DEFAULT}" PARENT_SCOPE)
    else()
        set(${out_var} "" PARENT_SCOPE)
    endif()
endfunction()

function(owalkie_ios_triplet_from_cmake out_var)
    if(NOT CMAKE_OSX_SYSROOT MATCHES ".*simulator.*")
        set(${out_var} "arm64-ios" PARENT_SCOPE)
        return()
    endif()
    if(CMAKE_OSX_ARCHITECTURES MATCHES "x86_64")
        set(${out_var} "x64-ios-simulator" PARENT_SCOPE)
    else()
        set(${out_var} "arm64-ios-simulator" PARENT_SCOPE)
    endif()
endfunction()

function(owalkie_pin_vcpkg_ios_dirs vcpkg_root triplet)
    set(_prefix "${vcpkg_root}/installed/${triplet}")
    set(VCPKG_INSTALLED_DIR "${_prefix}" CACHE PATH "vcpkg installed prefix" FORCE)
    set(Boost_DIR "${_prefix}/share/boost" CACHE PATH "" FORCE)
    set(Opus_DIR "${_prefix}/share/opus" CACHE PATH "" FORCE)
endfunction()

function(owalkie_ios_vcpkg_session_ready out_var)
    owalkie_resolve_vcpkg_root(_vcpkg_root)
    if("${_vcpkg_root}" STREQUAL "")
        set(${out_var} OFF PARENT_SCOPE)
        return()
    endif()
    owalkie_ios_triplet_from_cmake(_triplet)
    set(_prefix "${_vcpkg_root}/installed/${_triplet}")
    if(EXISTS "${_prefix}/share/boost_headers/boost_headers-config.cmake")
        set(${out_var} ON PARENT_SCOPE)
    else()
        set(${out_var} OFF PARENT_SCOPE)
    endif()
endfunction()

function(owalkie_assert_vcpkg_ios_installed)
    owalkie_resolve_vcpkg_root(_vcpkg_root)
    owalkie_ios_triplet_from_cmake(_triplet)
    set(_prefix "${_vcpkg_root}/installed/${_triplet}")
    if(NOT EXISTS "${_prefix}/share/boost/BoostConfig.cmake")
        message(FATAL_ERROR
            "Missing vcpkg packages for ${_triplet} under ${_vcpkg_root}.\n"
            "Run: flutter-client/ios/scripts/build-ios-deps.sh")
    endif()
endfunction()
